FROM mcr.microsoft.com/devcontainers/base:ubuntu

# Install Docker CLI and Python with pip
RUN apt-get update && \
    apt-get install -y docker.io python3 python3-pip && \
    pip3 install pymysql cryptography


